version: '3.8'

services:
  app:
    build: .
    container_name: student-management-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: anishroot
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    restart: always

  postgres:
    image: docker.io/library/postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anishroot
      POSTGRES_DB: student_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: